// OUI (Organizationally Unique Identifier) lookup service
// MAC address vendor identification using IEEE OUI registry

interface OUIEntry {
  oui: string;
  vendor: string;
}

// Common OUI database - subset of IEEE registry for performance
// This can be expanded or loaded from external source
const OUI_DATABASE: OUIEntry[] = [
  // Apple
  { oui: '00:03:93', vendor: 'Apple' },
  { oui: '00:0A:27', vendor: 'Apple' },
  { oui: '00:0A:95', vendor: 'Apple' },
  { oui: '00:0D:93', vendor: 'Apple' },
  { oui: '00:11:24', vendor: 'Apple' },
  { oui: '00:14:51', vendor: 'Apple' },
  { oui: '00:16:CB', vendor: 'Apple' },
  { oui: '00:17:F2', vendor: 'Apple' },
  { oui: '00:19:E3', vendor: 'Apple' },
  { oui: '00:1B:63', vendor: 'Apple' },
  { oui: '00:1C:B3', vendor: 'Apple' },
  { oui: '00:1E:C2', vendor: 'Apple' },
  { oui: '00:21:E9', vendor: 'Apple' },
  { oui: '00:22:41', vendor: 'Apple' },
  { oui: '00:23:12', vendor: 'Apple' },
  { oui: '00:23:DF', vendor: 'Apple' },
  { oui: '00:24:36', vendor: 'Apple' },
  { oui: '00:25:00', vendor: 'Apple' },
  { oui: '00:25:4B', vendor: 'Apple' },
  { oui: '00:25:BC', vendor: 'Apple' },
  { oui: '00:26:08', vendor: 'Apple' },
  { oui: '00:26:4A', vendor: 'Apple' },
  { oui: '00:26:B0', vendor: 'Apple' },
  { oui: '00:26:BB', vendor: 'Apple' },
  { oui: '04:0C:CE', vendor: 'Apple' },
  { oui: '04:15:52', vendor: 'Apple' },
  { oui: '04:1E:64', vendor: 'Apple' },
  { oui: '04:26:65', vendor: 'Apple' },
  { oui: '04:54:53', vendor: 'Apple' },
  { oui: '04:69:F8', vendor: 'Apple' },
  { oui: '04:DB:56', vendor: 'Apple' },
  { oui: '04:E5:36', vendor: 'Apple' },
  { oui: '04:F1:3E', vendor: 'Apple' },
  { oui: '04:F7:E4', vendor: 'Apple' },
  { oui: '08:00:07', vendor: 'Apple' },
  { oui: '08:6D:41', vendor: 'Apple' },
  { oui: '08:74:02', vendor: 'Apple' },
  { oui: '0C:3E:9F', vendor: 'Apple' },
  { oui: '0C:4D:E9', vendor: 'Apple' },
  { oui: '0C:74:C2', vendor: 'Apple' },
  { oui: '10:9A:DD', vendor: 'Apple' },
  { oui: '10:DD:B1', vendor: 'Apple' },
  { oui: '14:10:9F', vendor: 'Apple' },
  { oui: '14:7D:DA', vendor: 'Apple' },
  { oui: '14:98:77', vendor: 'Apple' },
  { oui: '14:BD:61', vendor: 'Apple' },
  { oui: '18:34:51', vendor: 'Apple' },
  { oui: '18:3D:A2', vendor: 'Apple' },
  { oui: '18:AF:61', vendor: 'Apple' },
  { oui: '18:E7:F4', vendor: 'Apple' },
  { oui: '1C:1A:C0', vendor: 'Apple' },
  { oui: '1C:36:BB', vendor: 'Apple' },
  { oui: '1C:9E:CC', vendor: 'Apple' },
  { oui: '1C:AB:A7', vendor: 'Apple' },
  { oui: '20:34:FB', vendor: 'Apple' },
  { oui: '20:3C:AE', vendor: 'Apple' },
  { oui: '20:A2:E4', vendor: 'Apple' },
  { oui: '24:A0:74', vendor: 'Apple' },
  { oui: '24:AB:81', vendor: 'Apple' },
  { oui: '24:F0:94', vendor: 'Apple' },
  { oui: '28:37:37', vendor: 'Apple' },
  { oui: '28:6A:BA', vendor: 'Apple' },
  { oui: '28:6A:E7', vendor: 'Apple' },
  { oui: '28:E0:2C', vendor: 'Apple' },
  { oui: '28:ED:6A', vendor: 'Apple' },
  { oui: '2C:1F:23', vendor: 'Apple' },
  { oui: '2C:B4:3A', vendor: 'Apple' },
  { oui: '30:10:B3', vendor: 'Apple' },
  { oui: '30:35:AD', vendor: 'Apple' },
  { oui: '30:6B:35', vendor: 'Apple' },
  { oui: '30:90:AB', vendor: 'Apple' },
  { oui: '30:F7:72', vendor: 'Apple' },
  { oui: '34:15:9E', vendor: 'Apple' },
  { oui: '34:36:3B', vendor: 'Apple' },
  { oui: '34:A3:95', vendor: 'Apple' },
  { oui: '34:AB:37', vendor: 'Apple' },
  { oui: '34:C0:59', vendor: 'Apple' },
  { oui: '38:CA:DA', vendor: 'Apple' },
  { oui: '3C:07:54', vendor: 'Apple' },
  { oui: '3C:15:C2', vendor: 'Apple' },
  { oui: '3C:2E:F9', vendor: 'Apple' },
  { oui: '40:3C:FC', vendor: 'Apple' },
  { oui: '40:B3:95', vendor: 'Apple' },
  { oui: '40:CB:C0', vendor: 'Apple' },
  { oui: '40:D3:2D', vendor: 'Apple' },
  { oui: '44:2A:60', vendor: 'Apple' },
  { oui: '44:4C:0C', vendor: 'Apple' },
  { oui: '44:D8:84', vendor: 'Apple' },
  { oui: '48:43:7C', vendor: 'Apple' },
  { oui: '48:74:6E', vendor: 'Apple' },
  { oui: '48:A1:95', vendor: 'Apple' },
  { oui: '48:BF:6B', vendor: 'Apple' },
  { oui: '4C:8D:79', vendor: 'Apple' },
  { oui: '4C:B1:99', vendor: 'Apple' },
  { oui: '50:32:37', vendor: 'Apple' },
  { oui: '50:82:D5', vendor: 'Apple' },
  { oui: '50:EA:D6', vendor: 'Apple' },
  { oui: '54:26:96', vendor: 'Apple' },
  { oui: '54:4E:90', vendor: 'Apple' },
  { oui: '54:72:4F', vendor: 'Apple' },
  { oui: '54:AE:27', vendor: 'Apple' },
  { oui: '54:E4:3A', vendor: 'Apple' },
  { oui: '58:1F:AA', vendor: 'Apple' },
  { oui: '58:55:CA', vendor: 'Apple' },
  { oui: '5C:59:48', vendor: 'Apple' },
  { oui: '5C:95:AE', vendor: 'Apple' },
  { oui: '5C:96:9D', vendor: 'Apple' },
  { oui: '5C:F5:DA', vendor: 'Apple' },
  { oui: '60:03:08', vendor: 'Apple' },
  { oui: '60:33:4B', vendor: 'Apple' },
  { oui: '60:5A:6B', vendor: 'Apple' },
  { oui: '60:8F:5C', vendor: 'Apple' },
  { oui: '60:C5:47', vendor: 'Apple' },
  { oui: '60:F4:45', vendor: 'Apple' },
  { oui: '60:FB:42', vendor: 'Apple' },
  { oui: '64:20:0C', vendor: 'Apple' },
  { oui: '64:76:BA', vendor: 'Apple' },
  { oui: '64:A3:CB', vendor: 'Apple' },
  { oui: '64:B0:A6', vendor: 'Apple' },
  { oui: '64:E6:82', vendor: 'Apple' },
  { oui: '68:26:CC', vendor: 'Apple' },
  { oui: '68:54:FD', vendor: 'Apple' },
  { oui: '68:7F:74', vendor: 'Apple' },
  { oui: '68:96:7B', vendor: 'Apple' },
  { oui: '68:A8:6D', vendor: 'Apple' },
  { oui: '68:AE:20', vendor: 'Apple' },
  { oui: '68:D9:3C', vendor: 'Apple' },
  { oui: '6C:19:8F', vendor: 'Apple' },
  { oui: '6C:40:08', vendor: 'Apple' },
  { oui: '6C:70:9F', vendor: 'Apple' },
  { oui: '6C:94:66', vendor: 'Apple' },
  { oui: '6C:AD:F8', vendor: 'Apple' },
  { oui: '70:11:24', vendor: 'Apple' },
  { oui: '70:48:0F', vendor: 'Apple' },
  { oui: '70:56:81', vendor: 'Apple' },
  { oui: '70:73:CB', vendor: 'Apple' },
  { oui: '70:CD:60', vendor: 'Apple' },
  { oui: '70:DE:E2', vendor: 'Apple' },
  { oui: '74:1B:B2', vendor: 'Apple' },
  { oui: '74:29:9E', vendor: 'Apple' },
  { oui: '74:2F:68', vendor: 'Apple' },
  { oui: '74:86:7A', vendor: 'Apple' },
  { oui: '74:E2:F5', vendor: 'Apple' },
  { oui: '74:E7:F6', vendor: 'Apple' },
  { oui: '78:31:C1', vendor: 'Apple' },
  { oui: '78:4F:43', vendor: 'Apple' },
  { oui: '78:7B:8A', vendor: 'Apple' },
  { oui: '78:A3:E4', vendor: 'Apple' },
  { oui: '78:CA:39', vendor: 'Apple' },
  { oui: '78:D7:5F', vendor: 'Apple' },
  { oui: '7C:04:D0', vendor: 'Apple' },
  { oui: '7C:6D:62', vendor: 'Apple' },
  { oui: '7C:C3:A1', vendor: 'Apple' },
  { oui: '7C:D1:C3', vendor: 'Apple' },
  { oui: '7C:F0:5F', vendor: 'Apple' },
  { oui: '80:00:6E', vendor: 'Apple' },
  { oui: '80:06:81', vendor: 'Apple' },
  { oui: '80:35:C1', vendor: 'Apple' },
  { oui: '80:92:9F', vendor: 'Apple' },
  { oui: '80:9B:20', vendor: 'Apple' },
  { oui: '80:E6:50', vendor: 'Apple' },
  { oui: '84:38:35', vendor: 'Apple' },
  { oui: '84:85:06', vendor: 'Apple' },
  { oui: '84:FC:FE', vendor: 'Apple' },
  { oui: '88:1F:A1', vendor: 'Apple' },
  { oui: '88:53:2E', vendor: 'Apple' },
  { oui: '88:63:DF', vendor: 'Apple' },
  { oui: '88:66:A5', vendor: 'Apple' },
  { oui: '88:6B:6E', vendor: 'Apple' },
  { oui: '88:AE:1D', vendor: 'Apple' },
  { oui: '88:C6:63', vendor: 'Apple' },
  { oui: '8C:29:37', vendor: 'Apple' },
  { oui: '8C:2D:AA', vendor: 'Apple' },
  { oui: '8C:58:77', vendor: 'Apple' },
  { oui: '8C:7C:92', vendor: 'Apple' },
  { oui: '8C:85:90', vendor: 'Apple' },
  { oui: '8C:8E:F2', vendor: 'Apple' },
  { oui: '90:27:E4', vendor: 'Apple' },
  { oui: '90:72:40', vendor: 'Apple' },
  { oui: '90:84:0D', vendor: 'Apple' },
  { oui: '90:9C:02', vendor: 'Apple' },
  { oui: '90:B2:1F', vendor: 'Apple' },
  { oui: '90:FD:61', vendor: 'Apple' },
  { oui: '94:E9:6A', vendor: 'Apple' },
  { oui: '94:F6:A3', vendor: 'Apple' },
  { oui: '98:03:D8', vendor: 'Apple' },
  { oui: '98:5A:EB', vendor: 'Apple' },
  { oui: '98:B8:E3', vendor: 'Apple' },
  { oui: '98:F0:AB', vendor: 'Apple' },
  { oui: '9C:04:EB', vendor: 'Apple' },
  { oui: '9C:20:7B', vendor: 'Apple' },
  { oui: '9C:29:3F', vendor: 'Apple' },
  { oui: '9C:84:BF', vendor: 'Apple' },
  { oui: '9C:F3:87', vendor: 'Apple' },
  { oui: 'A0:18:28', vendor: 'Apple' },
  { oui: 'A0:2B:BA', vendor: 'Apple' },
  { oui: 'A0:4E:A7', vendor: 'Apple' },
  { oui: 'A0:99:9B', vendor: 'Apple' },
  { oui: 'A0:C5:89', vendor: 'Apple' },
  { oui: 'A0:D7:95', vendor: 'Apple' },
  { oui: 'A0:E6:F8', vendor: 'Apple' },
  { oui: 'A4:31:35', vendor: 'Apple' },
  { oui: 'A4:5E:60', vendor: 'Apple' },
  { oui: 'A4:67:06', vendor: 'Apple' },
  { oui: 'A4:83:E7', vendor: 'Apple' },
  { oui: 'A4:B1:97', vendor: 'Apple' },
  { oui: 'A4:C3:61', vendor: 'Apple' },
  { oui: 'A4:D1:8C', vendor: 'Apple' },
  { oui: 'A8:20:66', vendor: 'Apple' },
  { oui: 'A8:51:AB', vendor: 'Apple' },
  { oui: 'A8:60:B6', vendor: 'Apple' },
  { oui: 'A8:88:08', vendor: 'Apple' },
  { oui: 'A8:96:8A', vendor: 'Apple' },
  { oui: 'A8:FA:D8', vendor: 'Apple' },
  { oui: 'AC:1F:74', vendor: 'Apple' },
  { oui: 'AC:29:3A', vendor: 'Apple' },
  { oui: 'AC:37:43', vendor: 'Apple' },
  { oui: 'AC:3C:0B', vendor: 'Apple' },
  { oui: 'AC:87:A3', vendor: 'Apple' },
  { oui: 'AC:BC:32', vendor: 'Apple' },
  { oui: 'AC:CF:5C', vendor: 'Apple' },
  { oui: 'AC:E4:B5', vendor: 'Apple' },
  { oui: 'AC:FD:CE', vendor: 'Apple' },
  { oui: 'B0:19:C6', vendor: 'Apple' },
  { oui: 'B0:34:95', vendor: 'Apple' },
  { oui: 'B0:65:BD', vendor: 'Apple' },
  { oui: 'B0:9F:BA', vendor: 'Apple' },
  { oui: 'B4:18:D1', vendor: 'Apple' },
  { oui: 'B4:3A:28', vendor: 'Apple' },
  { oui: 'B4:9C:DF', vendor: 'Apple' },
  { oui: 'B4:A5:AC', vendor: 'Apple' },
  { oui: 'B4:AE:2B', vendor: 'Apple' },
  { oui: 'B4:CE:F6', vendor: 'Apple' },
  { oui: 'B4:F0:AB', vendor: 'Apple' },
  { oui: 'B4:F6:1C', vendor: 'Apple' },
  { oui: 'B8:09:8A', vendor: 'Apple' },
  { oui: 'B8:17:C2', vendor: 'Apple' },
  { oui: 'B8:53:AC', vendor: 'Apple' },
  { oui: 'B8:63:BC', vendor: 'Apple' },
  { oui: 'B8:C7:5D', vendor: 'Apple' },
  { oui: 'B8:E8:56', vendor: 'Apple' },
  { oui: 'B8:F6:B1', vendor: 'Apple' },
  { oui: 'B8:FF:61', vendor: 'Apple' },
  { oui: 'BC:3B:AF', vendor: 'Apple' },
  { oui: 'BC:52:B7', vendor: 'Apple' },
  { oui: 'BC:67:1C', vendor: 'Apple' },
  { oui: 'BC:6C:21', vendor: 'Apple' },
  { oui: 'BC:92:6B', vendor: 'Apple' },
  { oui: 'BC:9F:EF', vendor: 'Apple' },
  { oui: 'BC:D0:74', vendor: 'Apple' },
  { oui: 'BC:EC:5D', vendor: 'Apple' },
  { oui: 'C0:18:50', vendor: 'Apple' },
  { oui: 'C0:25:A5', vendor: 'Apple' },
  { oui: 'C0:2F:2D', vendor: 'Apple' },
  { oui: 'C0:3F:D5', vendor: 'Apple' },
  { oui: 'C0:7C:D1', vendor: 'Apple' },
  { oui: 'C0:8A:DE', vendor: 'Apple' },
  { oui: 'C0:CC:F8', vendor: 'Apple' },
  { oui: 'C0:CE:CD', vendor: 'Apple' },
  { oui: 'C0:D0:12', vendor: 'Apple' },
  { oui: 'C4:2C:03', vendor: 'Apple' },
  { oui: 'C4:8E:8F', vendor: 'Apple' },
  { oui: 'C4:AD:34', vendor: 'Apple' },
  { oui: 'C4:B3:01', vendor: 'Apple' },
  { oui: 'C8:1E:E7', vendor: 'Apple' },
  { oui: 'C8:2A:14', vendor: 'Apple' },
  { oui: 'C8:33:4B', vendor: 'Apple' },
  { oui: 'C8:69:CD', vendor: 'Apple' },
  { oui: 'C8:6F:1D', vendor: 'Apple' },
  { oui: 'C8:85:50', vendor: 'Apple' },
  { oui: 'C8:89:F3', vendor: 'Apple' },
  { oui: 'C8:B5:B7', vendor: 'Apple' },
  { oui: 'C8:BC:C8', vendor: 'Apple' },
  { oui: 'C8:E0:EB', vendor: 'Apple' },
  { oui: 'C8:F6:50', vendor: 'Apple' },
  { oui: 'CC:08:8D', vendor: 'Apple' },
  { oui: 'CC:20:E8', vendor: 'Apple' },
  { oui: 'CC:25:EF', vendor: 'Apple' },
  { oui: 'CC:29:F5', vendor: 'Apple' },
  { oui: 'CC:2D:B7', vendor: 'Apple' },
  { oui: 'CC:6A:10', vendor: 'Apple' },
  { oui: 'CC:C7:60', vendor: 'Apple' },
  { oui: 'D0:03:4B', vendor: 'Apple' },
  { oui: 'D0:23:DB', vendor: 'Apple' },
  { oui: 'D0:A6:37', vendor: 'Apple' },
  { oui: 'D4:61:9D', vendor: 'Apple' },
  { oui: 'D4:9A:20', vendor: 'Apple' },
  { oui: 'D4:A3:3D', vendor: 'Apple' },
  { oui: 'D4:C9:EF', vendor: 'Apple' },
  { oui: 'D4:DC:CD', vendor: 'Apple' },
  { oui: 'D4:F4:6F', vendor: 'Apple' },
  { oui: 'D8:04:FF', vendor: 'Apple' },
  { oui: 'D8:30:62', vendor: 'Apple' },
  { oui: 'D8:96:95', vendor: 'Apple' },
  { oui: 'D8:A2:5E', vendor: 'Apple' },
  { oui: 'D8:BB:2C', vendor: 'Apple' },
  { oui: 'DC:2B:2A', vendor: 'Apple' },
  { oui: 'DC:37:45', vendor: 'Apple' },
  { oui: 'DC:3E:51', vendor: 'Apple' },
  { oui: 'DC:56:E7', vendor: 'Apple' },
  { oui: 'DC:9B:9C', vendor: 'Apple' },
  { oui: 'DC:A4:CA', vendor: 'Apple' },
  { oui: 'DC:A9:04', vendor: 'Apple' },
  { oui: 'DC:E5:5B', vendor: 'Apple' },
  { oui: 'DC:F8:56', vendor: 'Apple' },
  { oui: 'E0:2A:82', vendor: 'Apple' },
  { oui: 'E0:33:8E', vendor: 'Apple' },
  { oui: 'E0:35:FB', vendor: 'Apple' },
  { oui: 'E0:66:78', vendor: 'Apple' },
  { oui: 'E0:AC:CB', vendor: 'Apple' },
  { oui: 'E0:B5:2D', vendor: 'Apple' },
  { oui: 'E0:C9:7A', vendor: 'Apple' },
  { oui: 'E0:F5:C6', vendor: 'Apple' },
  { oui: 'E0:F8:47', vendor: 'Apple' },
  { oui: 'E4:25:E7', vendor: 'Apple' },
  { oui: 'E4:8B:7F', vendor: 'Apple' },
  { oui: 'E4:C6:3D', vendor: 'Apple' },
  { oui: 'E4:CE:8F', vendor: 'Apple' },
  { oui: 'E8:04:62', vendor: 'Apple' },
  { oui: 'E8:06:88', vendor: 'Apple' },
  { oui: 'E8:80:2E', vendor: 'Apple' },
  { oui: 'E8:B2:AC', vendor: 'Apple' },
  { oui: 'EC:35:86', vendor: 'Apple' },
  { oui: 'EC:8A:4B', vendor: 'Apple' },
  { oui: 'F0:18:98', vendor: 'Apple' },
  { oui: 'F0:4D:A2', vendor: 'Apple' },
  { oui: 'F0:5C:19', vendor: 'Apple' },
  { oui: 'F0:7F:06', vendor: 'Apple' },
  { oui: 'F0:B4:79', vendor: 'Apple' },
  { oui: 'F0:C7:7F', vendor: 'Apple' },
  { oui: 'F0:DB:E2', vendor: 'Apple' },
  { oui: 'F0:DC:E2', vendor: 'Apple' },
  { oui: 'F0:F6:1C', vendor: 'Apple' },
  { oui: 'F4:0E:01', vendor: 'Apple' },
  { oui: 'F4:1B:A1', vendor: 'Apple' },
  { oui: 'F4:31:C3', vendor: 'Apple' },
  { oui: 'F4:37:B7', vendor: 'Apple' },
  { oui: 'F4:5C:89', vendor: 'Apple' },
  { oui: 'F4:8B:32', vendor: 'Apple' },
  { oui: 'F4:93:9F', vendor: 'Apple' },
  { oui: 'F4:F1:5A', vendor: 'Apple' },
  { oui: 'F4:F9:51', vendor: 'Apple' },
  { oui: 'F8:16:54', vendor: 'Apple' },
  { oui: 'F8:1E:DF', vendor: 'Apple' },
  { oui: 'F8:27:93', vendor: 'Apple' },
  { oui: 'F8:2F:A8', vendor: 'Apple' },
  { oui: 'F8:77:B9', vendor: 'Apple' },
  { oui: 'F8:A9:D0', vendor: 'Apple' },
  { oui: 'F8:DB:7F', vendor: 'Apple' },
  { oui: 'F8:E4:3B', vendor: 'Apple' },
  { oui: 'F8:FF:C2', vendor: 'Apple' },
  { oui: 'FC:18:3C', vendor: 'Apple' },
  { oui: 'FC:25:3F', vendor: 'Apple' },
  { oui: 'FC:62:B9', vendor: 'Apple' },
  { oui: 'FC:64:BA', vendor: 'Apple' },
  { oui: 'FC:E9:98', vendor: 'Apple' },
  { oui: 'FC:FC:48', vendor: 'Apple' },

  // Samsung
  { oui: '00:0D:E5', vendor: 'Samsung' },
  { oui: '00:12:FB', vendor: 'Samsung' },
  { oui: '00:15:B9', vendor: 'Samsung' },
  { oui: '00:16:32', vendor: 'Samsung' },
  { oui: '00:16:6B', vendor: 'Samsung' },
  { oui: '00:17:D5', vendor: 'Samsung' },
  { oui: '00:1A:8A', vendor: 'Samsung' },
  { oui: '00:1D:25', vendor: 'Samsung' },
  { oui: '00:1E:7D', vendor: 'Samsung' },
  { oui: '00:1F:CC', vendor: 'Samsung' },
  { oui: '00:21:19', vendor: 'Samsung' },
  { oui: '00:23:39', vendor: 'Samsung' },
  { oui: '00:26:37', vendor: 'Samsung' },
  { oui: '04:18:D6', vendor: 'Samsung' },
  { oui: '04:FE:7F', vendor: 'Samsung' },
  { oui: '08:08:C2', vendor: 'Samsung' },
  { oui: '08:37:3D', vendor: 'Samsung' },
  { oui: '08:D4:2B', vendor: 'Samsung' },
  { oui: '0C:14:20', vendor: 'Samsung' },
  { oui: '0C:89:10', vendor: 'Samsung' },
  { oui: '10:1D:C0', vendor: 'Samsung' },
  { oui: '10:30:47', vendor: 'Samsung' },
  { oui: '10:77:B1', vendor: 'Samsung' },
  { oui: '14:7F:90', vendor: 'Samsung' },
  { oui: '18:3A:2D', vendor: 'Samsung' },
  { oui: '18:CF:5E', vendor: 'Samsung' },
  { oui: '1C:5A:3E', vendor: 'Samsung' },
  { oui: '20:64:32', vendor: 'Samsung' },
  { oui: '20:6B:E7', vendor: 'Samsung' },
  { oui: '24:4B:03', vendor: 'Samsung' },
  { oui: '24:4B:81', vendor: 'Samsung' },
  { oui: '28:39:5E', vendor: 'Samsung' },
  { oui: '28:E3:1F', vendor: 'Samsung' },
  { oui: '2C:44:01', vendor: 'Samsung' },
  { oui: '2C:5D:93', vendor: 'Samsung' },
  { oui: '30:07:4D', vendor: 'Samsung' },
  { oui: '30:3A:64', vendor: 'Samsung' },
  { oui: '30:5A:3A', vendor: 'Samsung' },
  { oui: '34:23:BA', vendor: 'Samsung' },
  { oui: '34:BE:00', vendor: 'Samsung' },
  { oui: '38:AA:3C', vendor: 'Samsung' },
  { oui: '3C:BD:D8', vendor: 'Samsung' },
  { oui: '40:0E:85', vendor: 'Samsung' },
  { oui: '40:4E:36', vendor: 'Samsung' },
  { oui: '40:5D:82', vendor: 'Samsung' },
  { oui: '44:5E:F3', vendor: 'Samsung' },
  { oui: '44:91:60', vendor: 'Samsung' },
  { oui: '48:5A:3F', vendor: 'Samsung' },
  { oui: '4C:3C:16', vendor: 'Samsung' },
  { oui: '4C:49:E3', vendor: 'Samsung' },
  { oui: '50:01:BB', vendor: 'Samsung' },
  { oui: '50:14:79', vendor: 'Samsung' },
  { oui: '50:32:75', vendor: 'Samsung' },
  { oui: '50:55:27', vendor: 'Samsung' },
  { oui: '50:B7:C3', vendor: 'Samsung' },
  { oui: '50:CC:F8', vendor: 'Samsung' },
  { oui: '54:88:0E', vendor: 'Samsung' },
  { oui: '58:21:70', vendor: 'Samsung' },
  { oui: '58:A2:B5', vendor: 'Samsung' },
  { oui: '5C:0A:5B', vendor: 'Samsung' },
  { oui: '5C:51:4F', vendor: 'Samsung' },
  { oui: '60:6D:C7', vendor: 'Samsung' },
  { oui: '60:A1:0A', vendor: 'Samsung' },
  { oui: '64:1C:B0', vendor: 'Samsung' },
  { oui: '68:EB:C5', vendor: 'Samsung' },
  { oui: '6C:83:36', vendor: 'Samsung' },
  { oui: '70:4D:7B', vendor: 'Samsung' },
  { oui: '70:F9:27', vendor: 'Samsung' },
  { oui: '74:45:CE', vendor: 'Samsung' },
  { oui: '78:1F:DB', vendor: 'Samsung' },
  { oui: '78:47:1D', vendor: 'Samsung' },
  { oui: '78:59:5E', vendor: 'Samsung' },
  { oui: '78:BD:BC', vendor: 'Samsung' },
  { oui: '7C:1C:4E', vendor: 'Samsung' },
  { oui: '7C:61:66', vendor: 'Samsung' },
  { oui: '80:18:A7', vendor: 'Samsung' },
  { oui: '80:57:19', vendor: 'Samsung' },
  { oui: '80:7A:BF', vendor: 'Samsung' },
  { oui: '84:25:3F', vendor: 'Samsung' },
  { oui: '84:38:38', vendor: 'Samsung' },
  { oui: '84:A1:D1', vendor: 'Samsung' },
  { oui: '88:30:8A', vendor: 'Samsung' },
  { oui: '88:32:9B', vendor: 'Samsung' },
  { oui: '8C:77:12', vendor: 'Samsung' },
  { oui: '8C:C8:CD', vendor: 'Samsung' },
  { oui: '90:18:7C', vendor: 'Samsung' },
  { oui: '94:51:03', vendor: 'Samsung' },
  { oui: '94:D7:71', vendor: 'Samsung' },
  { oui: '98:52:3D', vendor: 'Samsung' },
  { oui: '9C:02:98', vendor: 'Samsung' },
  { oui: '9C:65:B0', vendor: 'Samsung' },
  { oui: '9C:B6:54', vendor: 'Samsung' },
  { oui: 'A0:75:89', vendor: 'Samsung' },
  { oui: 'A0:82:1F', vendor: 'Samsung' },
  { oui: 'A4:EB:D3', vendor: 'Samsung' },
  { oui: 'A8:06:00', vendor: 'Samsung' },
  { oui: 'A8:DB:03', vendor: 'Samsung' },
  { oui: 'AC:5A:14', vendor: 'Samsung' },
  { oui: 'AC:61:75', vendor: 'Samsung' },
  { oui: 'B0:79:94', vendor: 'Samsung' },
  { oui: 'B4:62:93', vendor: 'Samsung' },
  { oui: 'B4:74:9F', vendor: 'Samsung' },
  { oui: 'B8:5E:7B', vendor: 'Samsung' },
  { oui: 'BC:44:86', vendor: 'Samsung' },
  { oui: 'BC:79:AD', vendor: 'Samsung' },
  { oui: 'BC:85:1F', vendor: 'Samsung' },
  { oui: 'BC:F5:AC', vendor: 'Samsung' },
  { oui: 'C0:25:E9', vendor: 'Samsung' },
  { oui: 'C4:42:02', vendor: 'Samsung' },
  { oui: 'C4:5B:BE', vendor: 'Samsung' },
  { oui: 'C8:19:F7', vendor: 'Samsung' },
  { oui: 'C8:3A:6B', vendor: 'Samsung' },
  { oui: 'CC:07:AB', vendor: 'Samsung' },
  { oui: 'CC:B1:1A', vendor: 'Samsung' },
  { oui: 'D0:22:BE', vendor: 'Samsung' },
  { oui: 'D0:59:E4', vendor: 'Samsung' },
  { oui: 'D4:87:D8', vendor: 'Samsung' },
  { oui: 'D4:E8:B2', vendor: 'Samsung' },
  { oui: 'D8:90:E8', vendor: 'Samsung' },
  { oui: 'DC:71:44', vendor: 'Samsung' },
  { oui: 'E0:DB:10', vendor: 'Samsung' },
  { oui: 'E8:03:9A', vendor: 'Samsung' },
  { oui: 'E8:11:32', vendor: 'Samsung' },
  { oui: 'E8:50:8B', vendor: 'Samsung' },
  { oui: 'EC:1F:72', vendor: 'Samsung' },
  { oui: 'F0:25:B7', vendor: 'Samsung' },
  { oui: 'F4:0E:22', vendor: 'Samsung' },
  { oui: 'F4:7B:5E', vendor: 'Samsung' },
  { oui: 'F8:04:2E', vendor: 'Samsung' },
  { oui: 'F8:A9:D0', vendor: 'Samsung' },
  { oui: 'FC:00:12', vendor: 'Samsung' },

  // Intel
  { oui: '00:02:B3', vendor: 'Intel' },
  { oui: '00:03:47', vendor: 'Intel' },
  { oui: '00:04:23', vendor: 'Intel' },
  { oui: '00:07:E9', vendor: 'Intel' },
  { oui: '00:0E:35', vendor: 'Intel' },
  { oui: '00:12:F0', vendor: 'Intel' },
  { oui: '00:13:CE', vendor: 'Intel' },
  { oui: '00:15:00', vendor: 'Intel' },
  { oui: '00:16:76', vendor: 'Intel' },
  { oui: '00:19:D1', vendor: 'Intel' },
  { oui: '00:1B:77', vendor: 'Intel' },
  { oui: '00:1C:BF', vendor: 'Intel' },
  { oui: '00:1E:64', vendor: 'Intel' },
  { oui: '00:1E:65', vendor: 'Intel' },
  { oui: '00:1F:3B', vendor: 'Intel' },
  { oui: '00:21:6A', vendor: 'Intel' },
  { oui: '00:22:FB', vendor: 'Intel' },
  { oui: '00:24:D7', vendor: 'Intel' },
  { oui: '00:26:C6', vendor: 'Intel' },
  { oui: '00:27:10', vendor: 'Intel' },
  { oui: '04:79:70', vendor: 'Intel' },
  { oui: '08:11:96', vendor: 'Intel' },
  { oui: '0C:8B:FD', vendor: 'Intel' },
  { oui: '18:3D:A2', vendor: 'Intel' },
  { oui: '18:5E:0F', vendor: 'Intel' },
  { oui: '18:CC:18', vendor: 'Intel' },
  { oui: '1C:69:7A', vendor: 'Intel' },
  { oui: '1C:87:2C', vendor: 'Intel' },
  { oui: '20:16:B9', vendor: 'Intel' },
  { oui: '24:77:03', vendor: 'Intel' },
  { oui: '24:FD:52', vendor: 'Intel' },
  { oui: '28:5A:EB', vendor: 'Intel' },
  { oui: '28:C2:DD', vendor: 'Intel' },
  { oui: '28:E7:CF', vendor: 'Intel' },
  { oui: '2C:44:FD', vendor: 'Intel' },
  { oui: '2C:6E:85', vendor: 'Intel' },
  { oui: '30:E1:71', vendor: 'Intel' },
  { oui: '34:02:86', vendor: 'Intel' },
  { oui: '34:13:E8', vendor: 'Intel' },
  { oui: '34:F3:9A', vendor: 'Intel' },
  { oui: '38:59:F9', vendor: 'Intel' },
  { oui: '3C:A9:F4', vendor: 'Intel' },
  { oui: '3C:F8:62', vendor: 'Intel' },
  { oui: '40:74:E0', vendor: 'Intel' },
  { oui: '44:85:00', vendor: 'Intel' },
  { oui: '48:45:20', vendor: 'Intel' },
  { oui: '48:51:B7', vendor: 'Intel' },
  { oui: '4C:34:88', vendor: 'Intel' },
  { oui: '4C:80:93', vendor: 'Intel' },
  { oui: '50:76:AF', vendor: 'Intel' },
  { oui: '54:3A:A0', vendor: 'Intel' },
  { oui: '58:20:B1', vendor: 'Intel' },
  { oui: '58:94:6B', vendor: 'Intel' },
  { oui: '5C:E0:C5', vendor: 'Intel' },
  { oui: '64:00:6A', vendor: 'Intel' },
  { oui: '64:27:37', vendor: 'Intel' },
  { oui: '68:07:15', vendor: 'Intel' },
  { oui: '6C:0B:84', vendor: 'Intel' },
  { oui: '6C:29:95', vendor: 'Intel' },
  { oui: '74:E5:43', vendor: 'Intel' },
  { oui: '7C:7A:91', vendor: 'Intel' },
  { oui: '7C:B2:1B', vendor: 'Intel' },
  { oui: '80:19:34', vendor: 'Intel' },
  { oui: '80:86:F2', vendor: 'Intel' },
  { oui: '84:3A:4B', vendor: 'Intel' },
  { oui: '88:75:56', vendor: 'Intel' },
  { oui: '8C:A9:82', vendor: 'Intel' },
  { oui: '90:48:9A', vendor: 'Intel' },
  { oui: '90:E2:BA', vendor: 'Intel' },
  { oui: '94:65:9C', vendor: 'Intel' },
  { oui: '9C:B6:D0', vendor: 'Intel' },
  { oui: 'A0:88:69', vendor: 'Intel' },
  { oui: 'A0:C5:89', vendor: 'Intel' },
  { oui: 'A4:4C:C8', vendor: 'Intel' },
  { oui: 'A4:BB:6D', vendor: 'Intel' },
  { oui: 'A4:C3:F0', vendor: 'Intel' },
  { oui: 'AC:2B:6E', vendor: 'Intel' },
  { oui: 'AC:67:5D', vendor: 'Intel' },
  { oui: 'B4:96:91', vendor: 'Intel' },
  { oui: 'B8:AE:ED', vendor: 'Intel' },
  { oui: 'C4:8E:8F', vendor: 'Intel' },
  { oui: 'C8:21:58', vendor: 'Intel' },
  { oui: 'CC:2F:71', vendor: 'Intel' },
  { oui: 'D0:7E:35', vendor: 'Intel' },
  { oui: 'D4:25:8B', vendor: 'Intel' },
  { oui: 'D4:6A:6A', vendor: 'Intel' },
  { oui: 'D4:BE:D9', vendor: 'Intel' },
  { oui: 'D8:9E:F3', vendor: 'Intel' },
  { oui: 'DC:53:60', vendor: 'Intel' },
  { oui: 'E0:94:67', vendor: 'Intel' },
  { oui: 'E4:A4:71', vendor: 'Intel' },
  { oui: 'E8:2A:EA', vendor: 'Intel' },
  { oui: 'F0:D5:BF', vendor: 'Intel' },
  { oui: 'F4:06:69', vendor: 'Intel' },
  { oui: 'F8:63:94', vendor: 'Intel' },
  { oui: 'FC:77:74', vendor: 'Intel' },

  // Google
  { oui: '00:1A:11', vendor: 'Google' },
  { oui: '18:B4:30', vendor: 'Google' },
  { oui: '3C:5A:B4', vendor: 'Google' },
  { oui: '48:57:02', vendor: 'Google' },
  { oui: '54:60:09', vendor: 'Google' },
  { oui: '6C:AD:F8', vendor: 'Google' },
  { oui: '84:F5:A7', vendor: 'Google' },
  { oui: 'A4:77:33', vendor: 'Google' },
  { oui: 'A8:A0:19', vendor: 'Google' },
  { oui: 'B4:F5:AC', vendor: 'Google' },
  { oui: 'CC:3A:61', vendor: 'Google' },
  { oui: 'D8:80:39', vendor: 'Google' },
  { oui: 'DA:A1:19', vendor: 'Google' },
  { oui: 'DC:A6:32', vendor: 'Google' },
  { oui: 'E8:DE:27', vendor: 'Google' },
  { oui: 'F0:EF:86', vendor: 'Google' },
  { oui: 'F4:F5:D8', vendor: 'Google' },
  { oui: 'F8:8F:CA', vendor: 'Google' },

  // Microsoft
  { oui: '00:03:FF', vendor: 'Microsoft' },
  { oui: '00:0D:3A', vendor: 'Microsoft' },
  { oui: '00:12:5A', vendor: 'Microsoft' },
  { oui: '00:15:5D', vendor: 'Microsoft' },
  { oui: '00:17:FA', vendor: 'Microsoft' },
  { oui: '00:1D:D8', vendor: 'Microsoft' },
  { oui: '00:21:70', vendor: 'Microsoft' },
  { oui: '00:50:F2', vendor: 'Microsoft' },
  { oui: '02:80:37', vendor: 'Microsoft' },
  { oui: '1C:B7:2C', vendor: 'Microsoft' },
  { oui: '30:59:B7', vendor: 'Microsoft' },
  { oui: '34:88:5D', vendor: 'Microsoft' },
  { oui: '3C:A8:2A', vendor: 'Microsoft' },
  { oui: '40:6C:8F', vendor: 'Microsoft' },
  { oui: '50:1A:C5', vendor: 'Microsoft' },
  { oui: '60:45:BD', vendor: 'Microsoft' },
  { oui: '7C:2F:80', vendor: 'Microsoft' },
  { oui: '90:84:0D', vendor: 'Microsoft' },
  { oui: 'A0:CE:C8', vendor: 'Microsoft' },
  { oui: 'E0:CB:EE', vendor: 'Microsoft' },

  // Cisco
  { oui: '00:00:0C', vendor: 'Cisco' },
  { oui: '00:01:42', vendor: 'Cisco' },
  { oui: '00:01:63', vendor: 'Cisco' },
  { oui: '00:01:64', vendor: 'Cisco' },
  { oui: '00:01:96', vendor: 'Cisco' },
  { oui: '00:01:97', vendor: 'Cisco' },
  { oui: '00:01:C7', vendor: 'Cisco' },
  { oui: '00:02:16', vendor: 'Cisco' },
  { oui: '00:02:17', vendor: 'Cisco' },
  { oui: '00:02:3D', vendor: 'Cisco' },
  { oui: '00:02:4A', vendor: 'Cisco' },
  { oui: '00:02:4B', vendor: 'Cisco' },
  { oui: '00:02:7D', vendor: 'Cisco' },
  { oui: '00:02:7E', vendor: 'Cisco' },
  { oui: '00:02:B9', vendor: 'Cisco' },
  { oui: '00:02:BA', vendor: 'Cisco' },
  { oui: '00:02:FC', vendor: 'Cisco' },
  { oui: '00:02:FD', vendor: 'Cisco' },
  { oui: '00:03:31', vendor: 'Cisco' },
  { oui: '00:03:32', vendor: 'Cisco' },
  { oui: '00:03:6B', vendor: 'Cisco' },
  { oui: '00:03:6C', vendor: 'Cisco' },
  { oui: '00:03:9F', vendor: 'Cisco' },
  { oui: '00:03:A0', vendor: 'Cisco' },
  { oui: '00:03:E3', vendor: 'Cisco' },
  { oui: '00:03:FD', vendor: 'Cisco' },
  { oui: '00:03:FE', vendor: 'Cisco' },
  { oui: '00:04:28', vendor: 'Cisco' },
  { oui: '00:04:27', vendor: 'Cisco' },
  { oui: '00:04:4D', vendor: 'Cisco' },
  { oui: '00:04:6D', vendor: 'Cisco' },
  { oui: '00:04:9A', vendor: 'Cisco' },
  { oui: '00:04:C0', vendor: 'Cisco' },
  { oui: '00:04:C1', vendor: 'Cisco' },
  { oui: '00:04:DD', vendor: 'Cisco' },
  { oui: '00:05:00', vendor: 'Cisco' },
  { oui: '00:05:31', vendor: 'Cisco' },
  { oui: '00:05:32', vendor: 'Cisco' },
  { oui: '00:05:5E', vendor: 'Cisco' },
  { oui: '00:05:73', vendor: 'Cisco' },
  { oui: '00:05:74', vendor: 'Cisco' },
  { oui: '00:05:9A', vendor: 'Cisco' },
  { oui: '00:05:DC', vendor: 'Cisco' },
  { oui: '00:05:DD', vendor: 'Cisco' },
  { oui: '00:06:28', vendor: 'Cisco' },
  { oui: '00:06:52', vendor: 'Cisco' },
  { oui: '00:06:53', vendor: 'Cisco' },
  { oui: '00:06:7C', vendor: 'Cisco' },
  { oui: '00:06:C1', vendor: 'Cisco' },
  { oui: '00:06:D6', vendor: 'Cisco' },
  { oui: '00:06:D7', vendor: 'Cisco' },
  { oui: '00:07:0D', vendor: 'Cisco' },
  { oui: '00:07:0E', vendor: 'Cisco' },
  { oui: '00:07:4F', vendor: 'Cisco' },
  { oui: '00:07:50', vendor: 'Cisco' },
  { oui: '00:07:84', vendor: 'Cisco' },
  { oui: '00:07:85', vendor: 'Cisco' },
  { oui: '00:07:B3', vendor: 'Cisco' },
  { oui: '00:07:B4', vendor: 'Cisco' },
  { oui: '00:07:EB', vendor: 'Cisco' },
  { oui: '00:08:20', vendor: 'Cisco' },
  { oui: '00:08:21', vendor: 'Cisco' },
  { oui: '00:08:30', vendor: 'Cisco' },
  { oui: '00:08:31', vendor: 'Cisco' },
  { oui: '00:08:7C', vendor: 'Cisco' },
  { oui: '00:08:A3', vendor: 'Cisco' },
  { oui: '00:08:C2', vendor: 'Cisco' },
  { oui: '00:08:E2', vendor: 'Cisco' },
  { oui: '00:08:E3', vendor: 'Cisco' },
  { oui: '00:09:11', vendor: 'Cisco' },
  { oui: '00:09:12', vendor: 'Cisco' },
  { oui: '00:09:43', vendor: 'Cisco' },
  { oui: '00:09:44', vendor: 'Cisco' },
  { oui: '00:09:7B', vendor: 'Cisco' },
  { oui: '00:09:B7', vendor: 'Cisco' },
  { oui: '00:09:E8', vendor: 'Cisco' },
  { oui: '00:09:E9', vendor: 'Cisco' },
  { oui: '00:0A:41', vendor: 'Cisco' },
  { oui: '00:0A:42', vendor: 'Cisco' },
  { oui: '00:0A:8A', vendor: 'Cisco' },
  { oui: '00:0A:8B', vendor: 'Cisco' },
  { oui: '00:0A:B7', vendor: 'Cisco' },
  { oui: '00:0A:B8', vendor: 'Cisco' },
  { oui: '00:0A:F3', vendor: 'Cisco' },
  { oui: '00:0A:F4', vendor: 'Cisco' },
  { oui: '00:0B:45', vendor: 'Cisco' },
  { oui: '00:0B:46', vendor: 'Cisco' },
  { oui: '00:0B:5F', vendor: 'Cisco' },
  { oui: '00:0B:60', vendor: 'Cisco' },
  { oui: '00:0B:85', vendor: 'Cisco' },
  { oui: '00:0B:BE', vendor: 'Cisco' },
  { oui: '00:0B:BF', vendor: 'Cisco' },
  { oui: '00:0B:FC', vendor: 'Cisco' },
  { oui: '00:0B:FD', vendor: 'Cisco' },
  { oui: '00:0C:30', vendor: 'Cisco' },
  { oui: '00:0C:31', vendor: 'Cisco' },
  { oui: '00:0C:41', vendor: 'Cisco' },
  { oui: '00:0C:85', vendor: 'Cisco' },
  { oui: '00:0C:86', vendor: 'Cisco' },
  { oui: '00:0C:CE', vendor: 'Cisco' },
  { oui: '00:0C:CF', vendor: 'Cisco' },
  { oui: '00:0D:28', vendor: 'Cisco' },
  { oui: '00:0D:29', vendor: 'Cisco' },
  { oui: '00:0D:65', vendor: 'Cisco' },
  { oui: '00:0D:66', vendor: 'Cisco' },
  { oui: '00:0D:BC', vendor: 'Cisco' },
  { oui: '00:0D:BD', vendor: 'Cisco' },
  { oui: '00:0D:EC', vendor: 'Cisco' },
  { oui: '00:0D:ED', vendor: 'Cisco' },
  { oui: '00:0E:08', vendor: 'Cisco' },
  { oui: '00:0E:38', vendor: 'Cisco' },
  { oui: '00:0E:39', vendor: 'Cisco' },
  { oui: '00:0E:83', vendor: 'Cisco' },
  { oui: '00:0E:84', vendor: 'Cisco' },
  { oui: '00:0E:D6', vendor: 'Cisco' },
  { oui: '00:0E:D7', vendor: 'Cisco' },
  { oui: '00:0F:23', vendor: 'Cisco' },
  { oui: '00:0F:24', vendor: 'Cisco' },
  { oui: '00:0F:34', vendor: 'Cisco' },
  { oui: '00:0F:35', vendor: 'Cisco' },
  { oui: '00:0F:8F', vendor: 'Cisco' },
  { oui: '00:0F:90', vendor: 'Cisco' },
  { oui: '00:0F:F7', vendor: 'Cisco' },
  { oui: '00:0F:F8', vendor: 'Cisco' },
  { oui: '00:10:07', vendor: 'Cisco' },
  { oui: '00:10:11', vendor: 'Cisco' },
  { oui: '00:10:29', vendor: 'Cisco' },
  { oui: '00:10:2F', vendor: 'Cisco' },
  { oui: '00:10:54', vendor: 'Cisco' },
  { oui: '00:10:79', vendor: 'Cisco' },
  { oui: '00:10:7B', vendor: 'Cisco' },
  { oui: '00:10:A6', vendor: 'Cisco' },
  { oui: '00:10:F6', vendor: 'Cisco' },
  { oui: '00:11:20', vendor: 'Cisco' },
  { oui: '00:11:21', vendor: 'Cisco' },
  { oui: '00:11:5C', vendor: 'Cisco' },
  { oui: '00:11:5D', vendor: 'Cisco' },
  { oui: '00:11:92', vendor: 'Cisco' },
  { oui: '00:11:93', vendor: 'Cisco' },
  { oui: '00:11:BB', vendor: 'Cisco' },
  { oui: '00:11:BC', vendor: 'Cisco' },
  { oui: '00:12:00', vendor: 'Cisco' },
  { oui: '00:12:01', vendor: 'Cisco' },
  { oui: '00:12:43', vendor: 'Cisco' },
  { oui: '00:12:44', vendor: 'Cisco' },
  { oui: '00:12:7F', vendor: 'Cisco' },
  { oui: '00:12:80', vendor: 'Cisco' },
  { oui: '00:12:D9', vendor: 'Cisco' },
  { oui: '00:12:DA', vendor: 'Cisco' },
  { oui: '00:13:10', vendor: 'Cisco' },
  { oui: '00:13:1A', vendor: 'Cisco' },
  { oui: '00:13:5F', vendor: 'Cisco' },
  { oui: '00:13:60', vendor: 'Cisco' },
  { oui: '00:13:7F', vendor: 'Cisco' },
  { oui: '00:13:80', vendor: 'Cisco' },
  { oui: '00:13:C3', vendor: 'Cisco' },
  { oui: '00:13:C4', vendor: 'Cisco' },
  { oui: '00:14:1B', vendor: 'Cisco' },
  { oui: '00:14:1C', vendor: 'Cisco' },
  { oui: '00:14:69', vendor: 'Cisco' },
  { oui: '00:14:6A', vendor: 'Cisco' },
  { oui: '00:14:A8', vendor: 'Cisco' },
  { oui: '00:14:A9', vendor: 'Cisco' },
  { oui: '00:14:BF', vendor: 'Cisco' },
  { oui: '00:14:F1', vendor: 'Cisco' },
  { oui: '00:14:F2', vendor: 'Cisco' },
  { oui: '00:15:2B', vendor: 'Cisco' },
  { oui: '00:15:2C', vendor: 'Cisco' },
  { oui: '00:15:62', vendor: 'Cisco' },
  { oui: '00:15:63', vendor: 'Cisco' },
  { oui: '00:15:C6', vendor: 'Cisco' },
  { oui: '00:15:C7', vendor: 'Cisco' },
  { oui: '00:15:F9', vendor: 'Cisco' },
  { oui: '00:15:FA', vendor: 'Cisco' },
  { oui: '00:16:46', vendor: 'Cisco' },
  { oui: '00:16:47', vendor: 'Cisco' },
  { oui: '00:16:9C', vendor: 'Cisco' },
  { oui: '00:16:9D', vendor: 'Cisco' },
  { oui: '00:16:C7', vendor: 'Cisco' },
  { oui: '00:16:C8', vendor: 'Cisco' },
  { oui: '00:17:0E', vendor: 'Cisco' },
  { oui: '00:17:33', vendor: 'Cisco' },
  { oui: '00:17:34', vendor: 'Cisco' },
  { oui: '00:17:59', vendor: 'Cisco' },
  { oui: '00:17:5A', vendor: 'Cisco' },
  { oui: '00:17:94', vendor: 'Cisco' },
  { oui: '00:17:95', vendor: 'Cisco' },
  { oui: '00:17:E0', vendor: 'Cisco' },
  { oui: '00:17:DF', vendor: 'Cisco' },
  { oui: '00:18:18', vendor: 'Cisco' },
  { oui: '00:18:19', vendor: 'Cisco' },
  { oui: '00:18:39', vendor: 'Cisco' },
  { oui: '00:18:68', vendor: 'Cisco' },
  { oui: '00:18:73', vendor: 'Cisco' },
  { oui: '00:18:74', vendor: 'Cisco' },
  { oui: '00:18:B9', vendor: 'Cisco' },
  { oui: '00:18:BA', vendor: 'Cisco' },
  { oui: '00:19:06', vendor: 'Cisco' },
  { oui: '00:19:07', vendor: 'Cisco' },
  { oui: '00:19:2F', vendor: 'Cisco' },
  { oui: '00:19:30', vendor: 'Cisco' },
  { oui: '00:19:55', vendor: 'Cisco' },
  { oui: '00:19:56', vendor: 'Cisco' },
  { oui: '00:19:A9', vendor: 'Cisco' },
  { oui: '00:19:AA', vendor: 'Cisco' },
  { oui: '00:19:E7', vendor: 'Cisco' },
  { oui: '00:19:E8', vendor: 'Cisco' },
  { oui: '00:1A:2F', vendor: 'Cisco' },
  { oui: '00:1A:30', vendor: 'Cisco' },
  { oui: '00:1A:6C', vendor: 'Cisco' },
  { oui: '00:1A:6D', vendor: 'Cisco' },
  { oui: '00:1A:A1', vendor: 'Cisco' },
  { oui: '00:1A:A2', vendor: 'Cisco' },
  { oui: '00:1A:E2', vendor: 'Cisco' },
  { oui: '00:1A:E3', vendor: 'Cisco' },
  { oui: '00:1B:0C', vendor: 'Cisco' },
  { oui: '00:1B:0D', vendor: 'Cisco' },
  { oui: '00:1B:2A', vendor: 'Cisco' },
  { oui: '00:1B:2B', vendor: 'Cisco' },
  { oui: '00:1B:53', vendor: 'Cisco' },
  { oui: '00:1B:54', vendor: 'Cisco' },
  { oui: '00:1B:67', vendor: 'Cisco' },
  { oui: '00:1B:8F', vendor: 'Cisco' },
  { oui: '00:1B:90', vendor: 'Cisco' },
  { oui: '00:1B:D4', vendor: 'Cisco' },
  { oui: '00:1B:D5', vendor: 'Cisco' },
  { oui: '00:1C:0E', vendor: 'Cisco' },
  { oui: '00:1C:0F', vendor: 'Cisco' },
  { oui: '00:1C:57', vendor: 'Cisco' },
  { oui: '00:1C:58', vendor: 'Cisco' },
  { oui: '00:1C:B0', vendor: 'Cisco' },
  { oui: '00:1C:B1', vendor: 'Cisco' },
  { oui: '00:1C:F6', vendor: 'Cisco' },
  { oui: '00:1C:F9', vendor: 'Cisco' },
  { oui: '00:1D:45', vendor: 'Cisco' },
  { oui: '00:1D:46', vendor: 'Cisco' },
  { oui: '00:1D:70', vendor: 'Cisco' },
  { oui: '00:1D:71', vendor: 'Cisco' },
  { oui: '00:1D:A1', vendor: 'Cisco' },
  { oui: '00:1D:A2', vendor: 'Cisco' },
  { oui: '00:1D:E5', vendor: 'Cisco' },
  { oui: '00:1D:E6', vendor: 'Cisco' },
  { oui: '00:1E:13', vendor: 'Cisco' },
  { oui: '00:1E:14', vendor: 'Cisco' },
  { oui: '00:1E:49', vendor: 'Cisco' },
  { oui: '00:1E:4A', vendor: 'Cisco' },
  { oui: '00:1E:6B', vendor: 'Cisco' },
  { oui: '00:1E:BD', vendor: 'Cisco' },
  { oui: '00:1E:BE', vendor: 'Cisco' },
  { oui: '00:1E:F6', vendor: 'Cisco' },
  { oui: '00:1E:F7', vendor: 'Cisco' },
  { oui: '00:1F:26', vendor: 'Cisco' },
  { oui: '00:1F:27', vendor: 'Cisco' },
  { oui: '00:1F:6C', vendor: 'Cisco' },
  { oui: '00:1F:6D', vendor: 'Cisco' },
  { oui: '00:1F:9D', vendor: 'Cisco' },
  { oui: '00:1F:9E', vendor: 'Cisco' },
  { oui: '00:1F:CA', vendor: 'Cisco' },
  { oui: '00:1F:CB', vendor: 'Cisco' },
  { oui: '00:21:1B', vendor: 'Cisco' },
  { oui: '00:21:1C', vendor: 'Cisco' },
  { oui: '00:21:55', vendor: 'Cisco' },
  { oui: '00:21:56', vendor: 'Cisco' },
  { oui: '00:21:A0', vendor: 'Cisco' },
  { oui: '00:21:A1', vendor: 'Cisco' },
  { oui: '00:21:BE', vendor: 'Cisco' },
  { oui: '00:21:D7', vendor: 'Cisco' },
  { oui: '00:21:D8', vendor: 'Cisco' },
  { oui: '00:22:0C', vendor: 'Cisco' },
  { oui: '00:22:0D', vendor: 'Cisco' },
  { oui: '00:22:55', vendor: 'Cisco' },
  { oui: '00:22:56', vendor: 'Cisco' },
  { oui: '00:22:90', vendor: 'Cisco' },
  { oui: '00:22:91', vendor: 'Cisco' },
  { oui: '00:22:BD', vendor: 'Cisco' },
  { oui: '00:22:BE', vendor: 'Cisco' },
  { oui: '00:22:CE', vendor: 'Cisco' },
  { oui: '00:23:04', vendor: 'Cisco' },
  { oui: '00:23:05', vendor: 'Cisco' },
  { oui: '00:23:33', vendor: 'Cisco' },
  { oui: '00:23:34', vendor: 'Cisco' },
  { oui: '00:23:5D', vendor: 'Cisco' },
  { oui: '00:23:5E', vendor: 'Cisco' },
  { oui: '00:23:AB', vendor: 'Cisco' },
  { oui: '00:23:AC', vendor: 'Cisco' },
  { oui: '00:23:BE', vendor: 'Cisco' },
  { oui: '00:23:EA', vendor: 'Cisco' },
  { oui: '00:23:EB', vendor: 'Cisco' },
  { oui: '00:24:13', vendor: 'Cisco' },
  { oui: '00:24:14', vendor: 'Cisco' },
  { oui: '00:24:50', vendor: 'Cisco' },
  { oui: '00:24:51', vendor: 'Cisco' },
  { oui: '00:24:C3', vendor: 'Cisco' },
  { oui: '00:24:C4', vendor: 'Cisco' },
  { oui: '00:24:F7', vendor: 'Cisco' },
  { oui: '00:24:F9', vendor: 'Cisco' },
  { oui: '00:25:2E', vendor: 'Cisco' },
  { oui: '00:25:45', vendor: 'Cisco' },
  { oui: '00:25:46', vendor: 'Cisco' },
  { oui: '00:25:83', vendor: 'Cisco' },
  { oui: '00:25:84', vendor: 'Cisco' },
  { oui: '00:25:B4', vendor: 'Cisco' },
  { oui: '00:25:B5', vendor: 'Cisco' },
  { oui: '00:26:0A', vendor: 'Cisco' },
  { oui: '00:26:0B', vendor: 'Cisco' },
  { oui: '00:26:51', vendor: 'Cisco' },
  { oui: '00:26:52', vendor: 'Cisco' },
  { oui: '00:26:98', vendor: 'Cisco' },
  { oui: '00:26:99', vendor: 'Cisco' },
  { oui: '00:26:CA', vendor: 'Cisco' },
  { oui: '00:26:CB', vendor: 'Cisco' },
  { oui: '00:30:19', vendor: 'Cisco' },
  { oui: '00:30:24', vendor: 'Cisco' },
  { oui: '00:30:40', vendor: 'Cisco' },
  { oui: '00:30:71', vendor: 'Cisco' },
  { oui: '00:30:78', vendor: 'Cisco' },
  { oui: '00:30:7B', vendor: 'Cisco' },
  { oui: '00:30:80', vendor: 'Cisco' },
  { oui: '00:30:85', vendor: 'Cisco' },
  { oui: '00:30:94', vendor: 'Cisco' },
  { oui: '00:30:96', vendor: 'Cisco' },
  { oui: '00:30:A3', vendor: 'Cisco' },
  { oui: '00:30:B6', vendor: 'Cisco' },
  { oui: '00:30:F2', vendor: 'Cisco' },
  { oui: '00:60:09', vendor: 'Cisco' },
  { oui: '00:60:2F', vendor: 'Cisco' },
  { oui: '00:60:3E', vendor: 'Cisco' },
  { oui: '00:60:47', vendor: 'Cisco' },
  { oui: '00:60:5C', vendor: 'Cisco' },
  { oui: '00:60:70', vendor: 'Cisco' },
  { oui: '00:60:83', vendor: 'Cisco' },
  { oui: '00:90:0C', vendor: 'Cisco' },
  { oui: '00:90:21', vendor: 'Cisco' },
  { oui: '00:90:2B', vendor: 'Cisco' },
  { oui: '00:90:5F', vendor: 'Cisco' },
  { oui: '00:90:6D', vendor: 'Cisco' },
  { oui: '00:90:86', vendor: 'Cisco' },
  { oui: '00:90:92', vendor: 'Cisco' },
  { oui: '00:90:A6', vendor: 'Cisco' },
  { oui: '00:90:AB', vendor: 'Cisco' },
  { oui: '00:90:B1', vendor: 'Cisco' },
  { oui: '00:90:BF', vendor: 'Cisco' },
  { oui: '00:90:F2', vendor: 'Cisco' },
  { oui: '00:A0:C9', vendor: 'Cisco' },
  { oui: '00:B0:64', vendor: 'Cisco' },
  { oui: '00:B0:8E', vendor: 'Cisco' },
  { oui: '00:C0:1D', vendor: 'Cisco' },
  { oui: '00:C0:B7', vendor: 'Cisco' },
  { oui: '00:D0:79', vendor: 'Cisco' },
  { oui: '00:D0:97', vendor: 'Cisco' },
  { oui: '00:D0:BA', vendor: 'Cisco' },
  { oui: '00:D0:BB', vendor: 'Cisco' },
  { oui: '00:D0:BC', vendor: 'Cisco' },
  { oui: '00:D0:C0', vendor: 'Cisco' },
  { oui: '00:D0:D3', vendor: 'Cisco' },
  { oui: '00:D0:E4', vendor: 'Cisco' },
  { oui: '00:D0:FF', vendor: 'Cisco' },
  { oui: '00:E0:14', vendor: 'Cisco' },
  { oui: '00:E0:1E', vendor: 'Cisco' },
  { oui: '00:E0:34', vendor: 'Cisco' },
  { oui: '00:E0:4F', vendor: 'Cisco' },
  { oui: '00:E0:A3', vendor: 'Cisco' },
  { oui: '00:E0:B0', vendor: 'Cisco' },
  { oui: '00:E0:F7', vendor: 'Cisco' },
  { oui: '00:E0:F9', vendor: 'Cisco' },
  { oui: '00:E0:FE', vendor: 'Cisco' },

  // Broadcom
  { oui: '00:0A:F7', vendor: 'Broadcom' },
  { oui: '00:10:18', vendor: 'Broadcom' },
  { oui: '00:37:6D', vendor: 'Broadcom' },
  { oui: '28:CF:E9', vendor: 'Broadcom' },
  { oui: 'A0:F3:C1', vendor: 'Broadcom' },
  { oui: 'D4:5D:64', vendor: 'Broadcom' },

  // Qualcomm
  { oui: '00:03:7F', vendor: 'Qualcomm' },
  { oui: '00:0A:F5', vendor: 'Qualcomm' },
  { oui: '00:22:58', vendor: 'Qualcomm' },
  { oui: '00:26:E8', vendor: 'Qualcomm' },
  { oui: '2C:AB:00', vendor: 'Qualcomm' },
  { oui: '88:12:AC', vendor: 'Qualcomm' },
  { oui: '9C:A6:15', vendor: 'Qualcomm' },

  // Nokia
  { oui: '00:02:EE', vendor: 'Nokia' },
  { oui: '00:11:9F', vendor: 'Nokia' },
  { oui: '00:18:0A', vendor: 'Nokia' },
  { oui: '00:19:2D', vendor: 'Nokia' },
  { oui: '00:1A:16', vendor: 'Nokia' },
  { oui: '00:1A:89', vendor: 'Nokia' },
  { oui: '00:1B:AF', vendor: 'Nokia' },
  { oui: '00:1C:35', vendor: 'Nokia' },
  { oui: '00:1D:6E', vendor: 'Nokia' },
  { oui: '00:1E:3A', vendor: 'Nokia' },
  { oui: '00:1F:01', vendor: 'Nokia' },
  { oui: '00:1F:5C', vendor: 'Nokia' },
  { oui: '00:21:08', vendor: 'Nokia' },
  { oui: '00:21:FE', vendor: 'Nokia' },
  { oui: '00:22:FC', vendor: 'Nokia' },
  { oui: '00:23:B4', vendor: 'Nokia' },
  { oui: '00:24:03', vendor: 'Nokia' },
  { oui: '00:25:47', vendor: 'Nokia' },
  { oui: '40:B4:CD', vendor: 'Nokia' },
  { oui: '6C:9B:02', vendor: 'Nokia' },
  { oui: '9C:DA:3E', vendor: 'Nokia' },

  // Huawei
  { oui: '00:0F:E2', vendor: 'Huawei' },
  { oui: '00:15:E9', vendor: 'Huawei' },
  { oui: '00:18:82', vendor: 'Huawei' },
  { oui: '00:1E:10', vendor: 'Huawei' },
  { oui: '00:25:9E', vendor: 'Huawei' },
  { oui: '00:46:4B', vendor: 'Huawei' },
  { oui: '00:E0:FC', vendor: 'Huawei' },
  { oui: '08:19:A6', vendor: 'Huawei' },
  { oui: '10:C6:1F', vendor: 'Huawei' },
  { oui: '14:75:90', vendor: 'Huawei' },
  { oui: '18:8B:9D', vendor: 'Huawei' },
  { oui: '1C:1D:67', vendor: 'Huawei' },
  { oui: '20:F3:A3', vendor: 'Huawei' },
  { oui: '24:69:68', vendor: 'Huawei' },
  { oui: '28:6E:D4', vendor: 'Huawei' },
  { oui: '2C:AB:EB', vendor: 'Huawei' },
  { oui: '34:6B:D3', vendor: 'Huawei' },
  { oui: '40:4E:36', vendor: 'Huawei' },
  { oui: '50:8F:4C', vendor: 'Huawei' },
  { oui: '54:25:EA', vendor: 'Huawei' },
  { oui: '58:2A:F7', vendor: 'Huawei' },
  { oui: '5C:C9:D3', vendor: 'Huawei' },
  { oui: '60:DE:44', vendor: 'Huawei' },
  { oui: '6C:92:BF', vendor: 'Huawei' },
  { oui: '74:A7:22', vendor: 'Huawei' },
  { oui: '78:F8:82', vendor: 'Huawei' },
  { oui: '7C:A2:3E', vendor: 'Huawei' },
  { oui: '84:A8:E4', vendor: 'Huawei' },
  { oui: '8C:34:FD', vendor: 'Huawei' },
  { oui: '94:04:9C', vendor: 'Huawei' },
  { oui: 'A4:C4:94', vendor: 'Huawei' },
  { oui: 'AC:E2:15', vendor: 'Huawei' },
  { oui: 'B0:5A:DA', vendor: 'Huawei' },
  { oui: 'B4:CD:27', vendor: 'Huawei' },
  { oui: 'BC:25:E4', vendor: 'Huawei' },
  { oui: 'C4:0B:CB', vendor: 'Huawei' },
  { oui: 'C8:BE:19', vendor: 'Huawei' },
  { oui: 'D4:20:B0', vendor: 'Huawei' },
  { oui: 'DC:D9:16', vendor: 'Huawei' },
  { oui: 'E0:19:1D', vendor: 'Huawei' },
  { oui: 'E8:CD:2D', vendor: 'Huawei' },
  { oui: 'F0:79:59', vendor: 'Huawei' },
  { oui: 'F4:4E:05', vendor: 'Huawei' },
  { oui: 'F8:E7:1E', vendor: 'Huawei' },

  // Xiaomi
  { oui: '04:CF:8C', vendor: 'Xiaomi' },
  { oui: '08:EA:40', vendor: 'Xiaomi' },
  { oui: '0C:1D:AF', vendor: 'Xiaomi' },
  { oui: '14:F6:5A', vendor: 'Xiaomi' },
  { oui: '28:6C:07', vendor: 'Xiaomi' },
  { oui: '34:80:B3', vendor: 'Xiaomi' },
  { oui: '34:CE:00', vendor: 'Xiaomi' },
  { oui: '3C:BD:D8', vendor: 'Xiaomi' },
  { oui: '50:8F:4C', vendor: 'Xiaomi' },
  { oui: '64:09:80', vendor: 'Xiaomi' },
  { oui: '68:DF:DD', vendor: 'Xiaomi' },
  { oui: '74:51:BA', vendor: 'Xiaomi' },
  { oui: '78:11:DC', vendor: 'Xiaomi' },
  { oui: '7C:1D:D9', vendor: 'Xiaomi' },
  { oui: '88:C3:97', vendor: 'Xiaomi' },
  { oui: '98:FA:9B', vendor: 'Xiaomi' },
  { oui: 'A0:86:C6', vendor: 'Xiaomi' },
  { oui: 'B0:E2:35', vendor: 'Xiaomi' },
  { oui: 'D4:97:0B', vendor: 'Xiaomi' },
  { oui: 'F0:B4:29', vendor: 'Xiaomi' },
  { oui: 'F8:A4:5F', vendor: 'Xiaomi' },

  // TP-Link
  { oui: '00:25:86', vendor: 'TP-Link' },
  { oui: '14:CC:20', vendor: 'TP-Link' },
  { oui: '20:4E:7F', vendor: 'TP-Link' },
  { oui: '50:C7:BF', vendor: 'TP-Link' },
  { oui: '60:E3:27', vendor: 'TP-Link' },
  { oui: '84:16:F9', vendor: 'TP-Link' },
  { oui: '98:DA:C4', vendor: 'TP-Link' },
  { oui: 'A0:F3:C1', vendor: 'TP-Link' },
  { oui: 'AC:84:C6', vendor: 'TP-Link' },
  { oui: 'B0:48:7A', vendor: 'TP-Link' },
  { oui: 'C0:4A:00', vendor: 'TP-Link' },
  { oui: 'D8:0D:17', vendor: 'TP-Link' },
  { oui: 'E8:DE:27', vendor: 'TP-Link' },
  { oui: 'F4:F2:6D', vendor: 'TP-Link' },

  // Realtek
  { oui: '00:E0:4C', vendor: 'Realtek' },
  { oui: '52:54:00', vendor: 'Realtek' },
  
  // Common Virtual/Random MAC prefixes
  { oui: '02:00:00', vendor: 'Locally Administered' },
  { oui: '06:00:00', vendor: 'Locally Administered' },
  { oui: '0A:00:00', vendor: 'Locally Administered' },
  { oui: '0E:00:00', vendor: 'Locally Administered' },
  { oui: '12:00:00', vendor: 'Locally Administered' },
  { oui: '16:00:00', vendor: 'Locally Administered' },
  { oui: '1A:00:00', vendor: 'Locally Administered' },
  { oui: '1E:00:00', vendor: 'Locally Administered' }
];

// Create a Map for faster lookups
const ouiMap = new Map<string, string>();

// Initialize OUI map
OUI_DATABASE.forEach(entry => {
  ouiMap.set(entry.oui.toUpperCase(), entry.vendor);
});

/**
 * Extract OUI from MAC address
 * @param macAddress - MAC address in any common format
 * @returns OUI prefix (first 3 octets) in format XX:XX:XX
 */
function extractOUI(macAddress: string): string {
  if (!macAddress) return '';
  
  // Remove common delimiters and convert to uppercase
  const cleanMac = macAddress.replace(/[-:.\s]/g, '').toUpperCase();
  
  // Extract first 6 characters (3 octets)
  if (cleanMac.length >= 6) {
    const oui = cleanMac.substring(0, 6);
    // Format as XX:XX:XX
    return `${oui.substring(0, 2)}:${oui.substring(2, 4)}:${oui.substring(4, 6)}`;
  }
  
  return '';
}

/**
 * Look up vendor by MAC address OUI
 * @param macAddress - MAC address to lookup
 * @returns Vendor name or null if not found
 */
export function lookupVendor(macAddress: string): string | null {
  const oui = extractOUI(macAddress);
  if (!oui) return null;
  
  return ouiMap.get(oui) || null;
}

/**
 * Enhanced client identification
 * @param macAddress - MAC address
 * @param hostName - Optional hostname
 * @param manufacturer - Optional existing manufacturer
 * @returns Enhanced identification string
 */
export function identifyClient(
  macAddress: string, 
  hostName?: string, 
  manufacturer?: string
): string {
  // If we have a hostname, prefer that
  if (hostName && hostName.toLowerCase() !== 'unknown' && hostName !== '') {
    return hostName;
  }
  
  // Try to get vendor from OUI lookup
  const vendor = lookupVendor(macAddress);
  if (vendor) {
    return vendor;
  }
  
  // Fall back to existing manufacturer if available
  if (manufacturer && manufacturer.toLowerCase() !== 'unknown' && manufacturer !== '') {
    return manufacturer;
  }
  
  // Check for locally administered (randomized) MAC addresses
  if (macAddress && isLocallyAdministered(macAddress)) {
    return 'Private Device';
  }
  
  // Last resort - return empty string (no "Unknown Device")
  return '';
}

/**
 * Check if MAC address is locally administered (randomized for privacy)
 * @param macAddress - MAC address to check
 * @returns true if locally administered
 */
function isLocallyAdministered(macAddress: string): boolean {
  if (!macAddress) return false;
  
  // Clean the MAC address
  const cleanMac = macAddress.replace(/[-:.\s]/g, '');
  if (cleanMac.length < 2) return false;
  
  // Get first octet
  const firstOctet = parseInt(cleanMac.substring(0, 2), 16);
  
  // Check if bit 1 (locally administered) is set
  return (firstOctet & 0x02) !== 0;
}

/**
 * Get device type suggestion based on vendor
 * @param vendor - Vendor name
 * @returns Suggested device type
 */
export function suggestDeviceType(vendor: string): string {
  if (!vendor) return '';
  
  const vendorLower = vendor.toLowerCase();
  
  if (vendorLower.includes('apple')) {
    return 'iOS Device';
  } else if (vendorLower.includes('samsung')) {
    return 'Android Device';
  } else if (vendorLower.includes('google')) {
    return 'Android Device';
  } else if (vendorLower.includes('microsoft')) {
    return 'Windows Device';
  } else if (vendorLower.includes('intel')) {
    return 'Computer';
  } else if (vendorLower.includes('cisco') || vendorLower.includes('tp-link') || vendorLower.includes('broadcom')) {
    return 'Network Equipment';
  } else if (vendorLower.includes('xiaomi') || vendorLower.includes('huawei') || vendorLower.includes('nokia')) {
    return 'Mobile Device';
  }
  
  return '';
}

/**
 * Export the OUI database for external use
 */
export { OUI_DATABASE };